In [2]:
import torch
import time
import numpy as np
device = 'mps' if torch.mps.is_available() else 'cpu' #'cuda' for Windows/Linus with an NVIDIA GPU
print(device)

mps


In [3]:
#randint = torch.randint(-100, 100, (6,))

#tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

#zeroes = torch.zeros(2, 3)

#ones = torch.ones(3, 4)

#input = torch.empty(2, 3)

#arange = torch.arange(5)

#linspace = torch.linspace(3, 10, steps = 5)

#logspace = torch.logspace(start = -10, end = 10, steps = 5)

#eye = torch.eye(5)

#a = torch.empty((2, 3), dtype = torch.int64)
#empty_like = torch.empty_like(a)

In [4]:
%%time
start_time = time.time()
#matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .10f}")

 0.0006070137
CPU times: user 683 μs, sys: 871 μs, total: 1.55 ms
Wall time: 787 μs


CPU time = how long it takes to execute in CPU  
Wall time = how long does it take in real time (CPU time + waiting time)

In [5]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

#GPU
start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")

#CPU
start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time: .8f}")

 0.10119295
 0.40756726


/var/folders/66/j271jmt17vv1ss7whdl_n5p00000gn/T/ipykernel_58153/3356150773.py:19: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [7]:
#torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax

#Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
#10% or 0.1 => 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
#Draw samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)

tensor([1, 1, 1, 1, 0, 1, 0, 1, 1, 1])


In [9]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [10]:
# tril => triangle lower
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [11]:
#triu => triangle upper
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [12]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [13]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [14]:
#we essentially flip the dimensions
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [15]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# nn.linear function -> from nn.module
# nn.module contains anything that has learnable parameters
# when we apply weight and a bias to a nn.module it learns those and becomes better and better
import torch.nn as